### ISSUE TITLE
Phase block contains variants from consecutive (different) chromosomes

### ISSUE THREAD

**Issue by andremho** [vibansal/HapCUT2#102] opened 2020-08-10 13:34 UTC
Hi,

We are using HapCUT2 (v. 1.1) to phase germline & somatic variants from Illumina exome-seq data (Human).
We have encountered an issue where we see a phase block containing variants from two consecutive chromosomes (in this case chr20 and 21).

The SPAN of the phaseblock is set to -53734530 despite spanning chromosomes 20 & 21. There is one variant on chr 20 (close to the end of the q-arm and the telomere region) and two variants on the end of the p-arm (close to the centromere) of chr 21.

We have also observed similar events when running HapCUT2 on mouse data.

As input to extracthairs we use a combined germline & somatic vcf.
We use fgbio HapCutToVCF to make a phased vcf from the hapcut2 phased output, but this crashes since the HC2 outfile has this block spanning chromosomes.

I couldn't find this issue reported elsewhere.
Have you seen this / have an idea about it (has it been fixed in newer releases)? Is there a way to turn of phasing across chromosomes?

Thanks, Andreas

**Comment by vibansal** [comment] 2020-08-10 18:40
We usually run HapCUT2 separately on individual chromosomes, so this issue does not arise. However, even when running on all chromosomes jointly, all fragments output by extractHAIRS are only for individual chromosomes, so a phase block should not contain variants from different chromosomes. 

If you can share a dataset to reproduce this error, that would be best. Alternatively, information from the output files relating to the variants on different chromosomes that are in the same block would be helpful.

**Comment by andremho** [comment] 2020-08-10 19:19
Thx for the quick response!
Unfortunately I cannot share the current dataset, but here is a screenshot of the phaseblock in the output .phased file containing the three variants.

![4830D6EB-16B4-4726-AF99-AA9791D56C38](https://user-images.githubusercontent.com/7516360/89821401-cf4bba00-db4e-11ea-973b-e9967ab31682.png)

**Comment by vibansal** [comment] 2020-08-11 20:30
Would it be possible to share the log (stderr) from extractHAIRS? You can send it via email if that works.

**Comment by andremho** [comment] 2020-08-13 11:14
I sent you the stderr from extracHAIRS and HAPCUT2 now by e-mail. Hope they shed some light on the issue.

**Comment by andremho** [comment] 2020-08-18 09:37
Did you receive my e-mail & the files? Have you had a chance to take a look at them?
Thanks!

**Comment by vibansal** [comment] 2020-08-18 20:56
I did receive the email and I have looked at the log files that you sent, but I am unable to determine if the problem is in extracthairs or hapcut2. I am trying to see if I can reproduce this error using 1000 Genomes exome data.

**Comment by andremho** [comment] 2020-08-19 12:35
Ok, great to know that you are looking into it. We have also seen it happening for some cases in mouse WES data. Also, for human samples the error does not occur for every sample (most of the time it runs fine).

**Comment by andremho** [comment] 2020-08-20 10:52
I can send you the output from EXTRACTHAIRS (fragment file) and matching vcf file for a mouse sample we have, which produces a similar error (phaseblock with variants from chr 17 and chr 18) when running hapcut2, if that would help with the debugging?

**Comment by vibansal** [comment] 2020-08-20 13:39
Yes, that would be helpful. Thanks.

**Comment by andremho** [comment] 2020-08-21 07:39
Sent the files by e-mail now

**Comment by vibansal** [comment] 2020-09-07 19:56
The error was due to using different VCF files for extracthairs and hapcut2. Closing this issue.

**Closed by vibansal** 2020-09-07 19:56 UTC
